// Code generated by alef — DO NOT EDIT.
// alef:hash:78e763fc73ac5a4ac831a41bceec1514c925c7e4cc0ce9f8b1f9a1dc1a359c37
package xberg

// RequireNativeSetup_1_2_1 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_2_1 = "1.2.1"
