// Code generated by alef — DO NOT EDIT.
// alef:hash:0cf6d0edaa7972fc46de794aa11c7478de8350d91a0a38f56aa1b8c9fef0940f
package xberg

// RequireNativeSetup_1_2_9 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_3_0 = "1.3.0"
