// Code generated by alef — DO NOT EDIT.
// alef:hash:fc964968ddf9444aefc7233b2fbd296e3976af7a48925b4bf4472f152cef0686
package xberg

// RequireNativeSetup_1_2_2 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_2_2 = "1.2.2"
