# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: validator_management."""

from xberg import clear_validators, list_validators


def test_validators_clear() -> None:
    """Clear all validators and verify list is empty."""
    clear_validators()


def test_validators_list() -> None:
    """List all registered validators."""
    result = list_validators()
    assert result is not None
