# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: reranker_backend_management."""

from xberg import clear_reranker_backends, list_reranker_backends


def test_clear_reranker_backends() -> None:
    """Clear all reranker backends and verify list is empty."""
    clear_reranker_backends()


def test_list_reranker_backends() -> None:
    """List all registered reranker backends."""
    result = list_reranker_backends()
    assert result is not None
