# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dc18b9bd4a5fb3cb0fa7ce0bcdeed000c7ee05edc977030c4e47986f56ab080b
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: code."""

import json
import os

import pytest
from xberg import ExtractInput, ExtractInputKind, extract


@pytest.mark.asyncio
async def test_code_shebang_detection() -> None:
    """Test language detection from shebang line via bytes input."""
    input_mock_base_url = os.environ["MOCK_SERVER_URL"] + "/fixtures/code_shebang_detection"
    input_json = '{"kind":"uri","mime_type":"text/x-source-code","uri":"$mock_url/code/script.sh"}'.replace(
        "$mock_url", input_mock_base_url
    )
    input_data = json.loads(input_json)
    input = ExtractInput(kind=ExtractInputKind("uri"), mime_type=input_data["mime_type"], uri=input_data["uri"])

    result = await extract(input)
    assert result.results[0].mime_type == "text/x-source-code"
    assert len(result.results[0].content) >= 10
    assert "build" in result.results[0].content
    assert "clean" in result.results[0].content
