# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0aeb23adee2802bcfbd7a3ecb6da2d9800a8d183917fe7acf733705401dfed8a
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module Xberg
  ## The version string for this package.
  VERSION = "1.2.0"
end
