# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:46096f341346c38e3cf01e8ab3c246d2268fa69e05bdfed323fa910cb787a5c0
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module Xberg
  ## The version string for this package.
  VERSION = "1.2.3"
end
