# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3ac3308f8433080753b4d2b234748b556d2d25da58deee43fa7f7cd706ef33ae
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module Xberg
  ## The version string for this package.
  VERSION = "1.2.4"
end
